### ISSUE TITLE
加载codedump失败

### ISSUE THREAD

**Issue by tomatoFQ** [noslate-project/andb#41]
CentOS Linux release 7.2.1511
lldb version 7.0.1
python 2.7

按照官网步骤配置的环境，跑不起来。我需要额外配置什么吗？
/home/work/andb/loader
x86_64
('build-id:', '5141090ddf3282bf654333ed2b406bd108e0fc38')
['lldb', '-x', '-o', 'com sc im /home/work/andb/init/lldbinit.py', '-S', '/home/work/andb/init/lldbpreinit.cmd', '-s', '/home/work/andb/init/lldbinit.cmd', '-f', '/root/.andb-dwf/node-v16.18.0/node', '-c', '/home/work/service/media/core.10364']
(lldb) command source -s 0 '/home/work/andb/init/lldbpreinit.cmd'
Executing commands in '/home/work/andb/init/lldbpreinit.cmd'.
(lldb) platform select --sysroot sysroot remote-linux
  Platform: remote-linux
 Connected: no
(lldb) setting set target.exec-search-paths "sysroot/lib64"
(lldb) target create "/root/.andb-dwf/node-v16.18.0/node" --core "/home/work/service/media/core.10364"
Core file '/home/work/service/media/core.10364' (x86_64) was loaded.
(lldb) com sc im /home/work/andb/init/lldbinit.py
lldbinit end
init lldb module
(lldb) command source -s 0 '/home/work/andb/init/lldbinit.cmd'
Executing commands in '/home/work/andb/init/lldbinit.cmd'.
(lldb) #sc print(lldb.target)
(lldb) #sc print(lldb.process)
(lldb) #sc print(lldb.debugger)
(lldb) # last load andb
(lldb) script import andb
(lldb) script andb.Load()
node
lldb.target:  node
lldb.process:  SBProcess: pid = 10364, state = stopped, threads = 11, executable = node
lldb debugger loaded
load Dwf /root/.andb-dwf/node-v16.18.0/node.typ
PointerSize: 8 
V8Version: 9.4.146.26
ReadAllConstsNoInheritesByList() takes 0.488 second(s).
loaded struct 'Bootstrapper'.
loaded struct 'Builtins'.
'v8::internal::Builtins.builtin_count' (0) = 1726
loaded struct 'CompilationCache'.
loaded struct 'CompilationSubCache'.
loaded struct 'Internals'.
loaded struct 'Isolate'.
loaded struct 'Node'.
loaded struct 'NodeSpace'.
loaded struct 'OnStackTracedNodeSpace'.
loaded struct 'GlobalHandles'.
loaded struct 'EternalHandles'.
loaded struct 'HandleScopeData'.
loaded struct 'DetachableVectorBase'.
loaded struct 'HandleScopeImplementer'.
loaded struct 'ExternalStringTable'.
loaded struct 'Heap'.
loaded struct 'ReadOnlyHeap'.
loaded struct 'ReadOnlyRoots'.
'v8::internal::ReadOnlyRoots.kEntriesCount' (0) = 590
loaded struct 'MemoryChunk'.
loaded struct 'RootsTable'.
'v8::internal::RootsTable.kEntriesCount' (0) = 672
loaded struct 'Space'.
loaded struct 'ReadOnlySpace'.
loaded struct 'Relocatable'.
loaded struct 'SourceCodeCache'.
loaded struct 'SourcePosition'.
loaded struct 'InterpreterData'.
loaded struct 'Representation'.
loaded struct 'Data'.
loaded struct 'StringTable'.
loaded struct 'SpaceWithLinearArea'.
loaded struct 'PagedSpace'.
loaded struct 'SemiSpace'.
loaded struct 'NewSpace'.
loaded enum 'AbortReason'.
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/work/andb/andb/__init__.py", line 18, in Load
    v8.LoadDwf()
  File "/home/work/andb/andb/v8/internal.py", line 1735, in LoadDwf
    Enum.LoadAllDwf()
  File "/home/work/andb/andb/dbg/base.py", line 153, in LoadAllDwf
    c.LoadDwf()
  File "/home/work/andb/andb/dbg/base.py", line 131, in LoadDwf
    for i in cls._E_type.GetEnumMembers():
  File "/home/work/andb/andb/dbg/dbg_lldb.py", line 376, in GetEnumMembers
    array = self._I_type.get_enum_members_array()
  File "/usr/lib64/python2.7/site-packages/lldb/__init__.py", line 8285, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, SBType, name)
  File "/usr/lib64/python2.7/site-packages/lldb/__init__.py", line 79, in _swig_getattr
    raise AttributeError(name)
AttributeError: get_enum_members_array

**Comment by tomatoFQ** [comment]
可以忽略，lldb的python包版本不对。更新后可以跑起来
