### ISSUE TITLE
解析core文件提示找不到node.typ

### ISSUE THREAD

**Issue by LvPeng990324** [noslate-project/andb#45]
我这边有用gcore工具抓取的core文件，根据README所说的，建立docker镜像后使用`andb node -g -c core3.1`尝试调试后报错`IOError: [Errno 2] No such file or directory: 'node.typ'`

然后才发现README里说gcore的要提供这个node.typ文件，但是我项目里没有这个文件，请问大佬这个文件是啥，咋生成的

以下是详细的错误信息：

```
[root@b32164ad64d2 ~]# andb -g node -c core3.1
/root/andb/loader
['gdb', '--nh', '--nx', '-ix', '/root/andb/init/gdbinit.cmd', '-x', '/root/andb/init/gdbinit.py', 'node', '--core', 'core3.1']
GNU gdb (GDB) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "--host=x86_64-pc-linux-gnu --target=x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from node...

warning: Can't open file /usr/local/node-v14.18.3-linux-x64/bin/node during file-backed mapping note processing

warning: Can't open file /usr/lib64/libresolv-2.17.so during file-backed mapping note processing

warning: Can't open file /usr/lib64/libnss_dns-2.17.so during file-backed mapping note processing

warning: Can't open file /usr/lib64/libnss_files-2.17.so during file-backed mapping note processing

warning: Can't open file /server/tyscyrj/src/node_modules/v8-profiler-next/build/binding/Release/node-v83-linux-x64/profiler.node during file-backed mapping note processing

warning: Can't open file /usr/lib64/libc-2.17.so during file-backed mapping note processing

warning: Can't open file /usr/lib64/libpthread-2.17.so during file-backed mapping note processing

warning: Can't open file /usr/lib64/libgcc_s-4.8.5-20150702.so.1 during file-backed mapping note processing

warning: Can't open file /usr/lib64/libm-2.17.so during file-backed mapping note processing

warning: Can't open file /usr/lib64/libstdc++.so.6.0.19 during file-backed mapping note processing

warning: Can't open file /usr/lib64/libdl-2.17.so during file-backed mapping note processing

warning: Can't open file /usr/lib64/libonion_security.so.1.0.19 during file-backed mapping note processing

warning: Can't open file /usr/lib64/ld-2.17.so during file-backed mapping note processing
[New LWP 17]
[New LWP 18]
[New LWP 19]
[New LWP 20]
[New LWP 21]
[New LWP 22]
[New LWP 23]
[New LWP 24]
[New LWP 25]
[New LWP 26]
[New LWP 1]

warning: Could not load shared library symbols for 12 libraries, e.g. /lib64/libonion.so.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
Core was generated by `/usr/local/node-v14.18.3-linux-x64/bin/node'.
#0  0x00007f34b64d0fd3 in ?? ()
[Current thread is 1 (LWP 17)]
******
Your encoding (ANSI_X3.4-1968) is different than UTF-8. might not work properly.
You might try launching gdb with:
    LC_ALL=en_US.UTF-8 PYTHONIOENCODING=UTF-8 gdb
Make sure that en_US.UTF-8 is activated in /etc/locale.gen and you called locale-gen
******
10.2
v8 unwinder registed.
gdb debugger loaded
load Dwf node.typ
add symbol table from file "node.typ"
Traceback (most recent call last):
  File "/root/andb/init/gdbinit.py", line 34, in <module>
    andb.Load()
  File "/root/andb/andb/__init__.py", line 14, in Load
    dbg.LoadDwf()
  File "/root/andb/andb/dbg/__init__.py", line 32, in LoadDwf
    Target.AddDwfFile(dwf_file)
  File "/root/andb/andb/dbg/dbg_gdb.py", line 674, in AddDwfFile
    gdb.execute("add-symbol-file '%s'" % filename)
gdb.error: node.typ: No such file or directory.
```

**Comment by zhaolei0505** [comment]
``` 
andb -g -c core3.1
```
请直接使用 -c 指定 corefile 文件, 如果是 andb 支持的官方发行版, 会自动下载匹配的 node 和 node.typ 文件.

**Comment by LvPeng990324** [comment]
> ```
> andb -g -c core3.1
> ```
> 
> 请直接使用 -c 指定 corefile 文件, 如果是 andb 支持的官方发行版, 会自动下载匹配的 node 和 node.typ 文件.

好的，我当时可能是网络环境问题，它自动下载失败了，后面尝试了一波成功了，谢谢解答！
